version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 wbe.wsgi:application
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: your_secret_key
      DJANGO_DEBUG: "True"  # Set to "False" in production
      STRIPE_PUBLISHABLE_KEY: your_stripe_publishable_key
      STRIPE_SECRET_KEY: your_stripe_secret_key
      SENTRY_DSN: your_sentry_dsn
      SUPERUSER_USERNAME: your_superuser_username
      SUPERUSER_EMAIL: your_superuser_email
      SUPERUSER_PASSWORD: your_superuser_password
    volumes:
      - .:/app
