version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 wbe.wsgi:application
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: "your_secret_key"
      DJANGO_DEBUG: "True"  # Set to False in production
      # Add other environment variables here
