# Generated by Django 5.0.3 on 2024-03-29 15:06

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(blank=True, max_length=255)),
                ('hero_button_text', models.CharField(blank=True, max_length=255)),
                ('hero_button_link', models.URLField(blank=True)),
                ('hero_image', imagekit.models.fields.ProcessedImageField(upload_to='hero_images/')),
            ],
        ),
    ]
