# Generated by Django 5.0.3 on 2024-03-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='page_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Page Title'),
        ),
    ]
