# Generated by Django 5.0.3 on 2024-03-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_homepage_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='seo_meta_description',
            field=models.TextField(blank=True, help_text='SEO Meta Description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='seo_title',
            field=models.CharField(blank=True, help_text='SEO Title', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='social_description',
            field=models.TextField(blank=True, help_text='Social Sharing Description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='social_image',
            field=models.ImageField(blank=True, help_text='Social Sharing Image', upload_to='social_images/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='social_image_alt',
            field=models.CharField(blank=True, help_text='Social Image Alt Text', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='social_title',
            field=models.CharField(blank=True, help_text='Social Sharing Title', max_length=255),
        ),
    ]
