# Generated by Django 5.0.3 on 2024-03-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_homepage_seo_keywords_homepage_seo_meta_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cutoff_days', models.IntegerField(help_text='Number of days before the event when refunds are no longer available.')),
                ('refund_percentage', models.DecimalField(decimal_places=2, help_text='Percentage of the entry fee that will be refunded if cancelled before the cutoff.', max_digits=5)),
            ],
        ),
    ]
