# Generated by Django 5.0.3 on 2024-03-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_privacypolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundpolicy',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='refundpolicy',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
