# Generated by Django 5.0.3 on 2024-03-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_refundpolicy_content_refundpolicy_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicy',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
