# Generated by Django 5.0.3 on 2024-03-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_privacypolicy_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsandConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
