# Generated by Django 5.0.3 on 2024-04-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_termsandconditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicy',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='refundpolicy',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
