# Generated by Django 5.0.3 on 2024-03-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('age_categories', '0001_initial'),
        ('event_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='age_categories',
            field=models.ManyToManyField(blank=True, related_name='races', to='age_categories.agecategory'),
        ),
    ]
