# Generated by Django 5.0.3 on 2024-03-29 13:46

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0003_venue_latitude_venue_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='hero_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='venues/'),
        ),
    ]
