# Generated by Django 5.0.3 on 2024-03-29 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('age_categories', '0001_initial'),
        ('event_management', '0005_event_description_event_last_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('club_team_name', models.CharField(blank=True, max_length=100)),
                ('entry_close_datetime', models.DateTimeField()),
                ('transfer_close_datetime', models.DateTimeField()),
                ('is_archived', models.BooleanField(default=False)),
                ('age_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='age_categories.agecategory')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='event_management.race')),
            ],
        ),
    ]
