# Generated by Django 5.0.3 on 2024-03-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0007_entry_user_race_refund_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='privacy_policy_accepted',
            field=models.BooleanField(default=False, verbose_name='I agree to the Privacy Policy'),
        ),
    ]
