# Generated by Django 5.0.3 on 2024-03-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0008_entry_privacy_policy_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='refund_policy_accepted',
            field=models.BooleanField(default=False, verbose_name='I agree to the Refund Policy'),
        ),
    ]
