# Generated by Django 5.0.3 on 2024-03-30 16:02
from django.db import migrations, models
import mptt.fields

class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0009_entry_refund_policy_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lft',
            field=models.PositiveIntegerField(null=True, editable=False),
        ),
        migrations.AddField(
            model_name='event',
            name='rght',
            field=models.PositiveIntegerField(null=True, editable=False),
        ),
        migrations.AddField(
            model_name='event',
            name='tree_id',
            field=models.PositiveIntegerField(null=True, editable=False),
        ),
        migrations.AddField(
            model_name='event',
            name='level',
            field=models.PositiveIntegerField(null=True, editable=False),
        ),
    ]
