# Generated by Django 5.0.3 on 2024-03-30 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0011_remove_event_depth_remove_event_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='numchild',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='path',
        ),
        migrations.AddField(
            model_name='venue',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_set', to='event_management.venue'),
        ),
    ]
