# Generated by Django 5.0.3 on 2024-03-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0013_remove_venue_parent_entry_depth_entry_numchild_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='numchild',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='path',
        ),
        migrations.RemoveField(
            model_name='event',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='race',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='race',
            name='numchild',
        ),
        migrations.RemoveField(
            model_name='race',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='race',
            name='path',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='numchild',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='path',
        ),
        migrations.AlterField(
            model_name='event',
            name='depth',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='numchild',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='path',
            field=models.CharField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
