# Generated by Django 5.0.3 on 2024-03-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0014_remove_entry_depth_remove_entry_numchild_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='entry_close_datetime',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='transfer_close_datetime',
        ),
        migrations.AddField(
            model_name='race',
            name='entry_close_datetime',
            field=models.DateTimeField("2024-01-01T00:00:00Z"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='race',
            name='transfer_close_datetime',
            field=models.DateTimeField("2024-01-01T00:00:00Z"),
            preserve_default=False,
        ),
    ]
