# Generated by Django 5.0.3 on 2024-03-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0015_remove_entry_entry_close_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='event',
            name='numchild',
        ),
        migrations.RemoveField(
            model_name='event',
            name='path',
        ),
        migrations.AlterField(
            model_name='race',
            name='entry_close_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='race',
            name='transfer_close_datetime',
            field=models.DateTimeField(),
        ),
    ]
