# Generated by Django 5.0.3 on 2024-03-31 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_termsandconditions'),
        ('event_management', '0018_venue_description_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='terms_and_conditions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='core.termsandconditions'),
        ),
        migrations.AddField(
            model_name='entry',
            name='terms_and_conditions_accepted',
            field=models.BooleanField(default=False, verbose_name='I agree to the Terms and Conditions'),
        ),
    ]
