# Generated by Django 5.0.3 on 2024-03-31 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0020_remove_entry_terms_and_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
