# Generated by Django 5.0.3 on 2024-03-31 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0021_entry_date_of_birth_entry_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entry_date',
            field=models.DateField(auto_now_add=True, null=0),
            preserve_default=False,
        ),
    ]
