# Generated by Django 5.0.3 on 2024-04-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0023_alter_entry_entry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='entry_fee',
            field=models.DecimalField(decimal_places=2, default=50, help_text='The fee for the entry.', max_digits=6),
            preserve_default=False,
        ),
    ]
