# Generated by Django 5.0.3 on 2024-04-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0024_race_entry_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='entry_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
