# Generated by Django 5.0.3 on 2024-04-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0026_entry_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
