name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
        django-version: ['5.0.3']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Django==${{ matrix.django-version }}
          pip install -r requirements.txt
          pip install pytest-django pytest pytest-cov
        env:
          PIP_NO_CACHE_DIR: "false"
          PIP_DISABLE_PIP_VERSION_CHECK: "1"
          PIP_DEFAULT_TIMEOUT: "100"

      - name: Set environment variables
        run: |
          echo "DJANGO_SETTINGS_MODULE=wbe.settings" >> $GITHUB_ENV
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
          echo "STRIPE_PUBLISHABLE_KEY=${{ secrets.STRIPE_PUBLISHABLE_KEY }}" >> $GITHUB_ENV

      - name: Add project to PYTHONPATH
        run: |
          echo "PYTHONPATH=${{ github.workspace }}/wbe" >> $GITHUB_ENV

      - name: Lint code with flake8
        run: |
          pip install flake8
          flake8 .
        continue-on-error: true

      - name: Run tests with pytest
        env:
          PYTHONPATH: ${{ github.workspace }}/wbe
        run: |
          pytest --cov=. --log-cli-level=DEBUG
        continue-on-error: false

      - name: Report coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
          flags: unittests
          name: codecov-report
          fail_ci_if_error: true
